name: '1.0$(Rev:.r)'
trigger:
- master

parameters:
- name: updateInfrastructure
  type: boolean
  default: false
  displayName: Update Infrastructure
  values:
    - true
    - false

variables:
  buildAgentVmImage: 'windows-latest'
  serviceConnection: 'niobium-invoicing'
  resourceGroupName: 'niobium-invoicing'
  appName: 'niobiuminvoicingFunc'
  tableDB: 'niobiuminvoicingdb'
  serviceBusNamespace: 'niobiuminvoicingsb'
  issueInvoiceCommandQueueName: 'issueinvoicecommand'
  enableStagingSlot: true

pool:
  vmImage: $(buildAgentVmImage)

resources: 
  repositories:
  - repository: devops
    endpoint: CodRepo
    type: git
    name: cod/Cod.Infrastructures
    ref: master

stages:
- stage: Production
  jobs:
  - template: pipelines/jobs/GenericDotnetBuild.yml@devops
    parameters:
      nugetVSTSFeedID: 'Niobium/niobium'
      projectToPublish: '**/Niobium.Invoicing.Functions.csproj'

  - template: pipelines/jobs/FunctionAppInfrastructure.yml@devops
    parameters:
      enabled: ${{ parameters.updateInfrastructure }}
      azureServiceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      appName: $(appName)
      enableKeyVault: true
      enableStagingSlot: ${{ variables.enableStagingSlot }}
      allowedOrigins: 'https://invoicing.niobium.co.nz'
      checkoutDevopsStep:
        checkout: devops

  - job: Table
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
    steps:
    - checkout: devops
    - template: pipelines/steps/newStorageAccount.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        storageAccountName: $(tableDB)
        contributorPrincipalId: $(functionAppPrincipalId)
        allowedOrigins: 'https://localhost:7182,https://invoicing.niobium.co.nz'

  - job: Messaging
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
    steps:
    - checkout: devops
    - template: pipelines/steps/newServiceBus.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        serviceBusNamespaceName: $(serviceBusNamespace)
        serviceBusQueueNames: [$(issueInvoiceCommandQueueName)]
        dataOwnerPrincipalId: $(functionAppPrincipalId)

  - job: Configuration
    dependsOn:
      - Infrastructure
      - Table
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      tableFQDN: $[dependencies.Table.outputs['newStorageAccountProperties.tableFQDN']]
      keyVaultUrl: $[dependencies.Infrastructure.outputs['infrastructureOutputs.keyVaultUrl']]
    steps:
    - checkout: none
    - pwsh: Write-Output "##vso[task.setvariable variable=slotName;]production"
      displayName: "Deploy to Production"
      condition: eq('${{ variables.enableStagingSlot }}', false)
    - pwsh: Write-Output "##vso[task.setvariable variable=slotName;]staging"
      displayName: "Deploy to Staging"
      condition: eq('${{ variables.enableStagingSlot }}', true)
    - task: AzureAppServiceSettings@1
      displayName: 'Update AppSettings'
      inputs:
        azureSubscription: $(serviceConnection)
        appName: $(appName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            {
              "name": "StorageTableOptions:FullyQualifiedDomainName",
              "value": "$(tableFQDN)",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:AccessTokenIssuer",
              "value": "Niobium.Invoicing.Functions",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:AccessTokenAudience",
              "value": "Niobium.Invoicing.Portal",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenAudience",
              "value": "95b52e52-dc79-4ac0-a53f-1acb10238888",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenPublicKey",
              "value": "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmuIHhRUT+IvTdTajuOEdPZ75pqJrajOyDdJqf42siofTKHCPCZqtWaftL8Jae5VMHUNCflXzm9aKTLgerAxrGyCL3BkZj/dj4KjbeFoY1Akz5EJd5qjRNtzdoqUkDsuaigJTDDhyHvdVKRHzYAJSKgiw9CLRkzyKDZAp1Fxm2xICzRoF9OfH0jv5Qn11gkMHrkVkB6nv7QD3EGS2rnDwKudjnlsvgjpoNMMNvY7EHqkuxjHdGh4Hy7M3UXl50Bft9ky3gKeCgpvVYRPXHdT6k3e+81J7liEJYdVb5taPeNf3wB8WCP8Xc7FO6vod9ziDIkJv+xqUWYtlyGZBGTBrQIDAQAB-----END PUBLIC KEY-----",
              "slotSetting": false
            },
            {
              "name": "ProfileOptions:ProfileServiceHost",
              "value": "https://codidentityfunc.azurewebsites.net",
              "slotSetting": false
            },
            {
              "name": "BillingOptions:GetInvoiceEndpoint",
              "value": "https://invoicing.niobium.co.nz",
              "slotSetting": false
            },
            {
              "name": "BillingOptions:InvoiceEmailSenderAddress",
              "value": "billing@niobium.co.nz",
              "slotSetting": false
            },
            {
              "name": "BillingOptions:InvoiceTokenSecretSalt",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/INVOICE-TOKEN-SECRET-SALT/)",
              "slotSetting": true
            },
            {
              "name": "IdentityServiceOptions:AccessTokenSecret",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/ACCESS-TOKEN-SECRET/)",
              "slotSetting": true
            },
            {
                "name": "ResendServiceOptions:GlobalAPIKey",
                "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/RESEND-API-KEY/)",
                "slotSetting": true
            },
            {
              "name": "StorageTableOptions:Key",
                "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/STORAGE-TABLE-KEY/)",
              "slotSetting": true
            }
          ]
    - task: AzureAppServiceSettings@1
      displayName: 'Update AppSettings'
      inputs:
        azureSubscription: $(serviceConnection)
        appName: $(appName)
        slotName: $(slotName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            
            {
              "name": "BillingOptions:InvoiceTokenSecretSalt",
              "value": "1234567890",
              "slotSetting": true
            },
            {
              "name": "IdentityServiceOptions:AccessTokenSecret",
              "value": "012345678901234567890123456789AB",
              "slotSetting": true
            },
            {
              "name": "AzureWebJobs.IssueInvoiceCommandConsumer.Disabled",
              "value": "true",
              "slotSetting": true
            }
          ]

  - template: pipelines/jobs/FunctionAppDeploy.yml@devops
    parameters:
      appName: $(appName)
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      enableStagingSlot: ${{ variables.enableStagingSlot }}
      autoSwapSlots: true
