name: '1.0$(Rev:.r)'
trigger:
- master

parameters:
- name: updateInfrastructure
  type: boolean
  default: false
  displayName: Update Infrastructure
  values:
    - true
    - false

variables:
  buildAgentVmImage: 'windows-latest'
  serviceConnection: 'niobium-billing'
  resourceGroupName: 'niobium-billing'

pool:
  vmImage: $(buildAgentVmImage)

resources: 
  repositories:
  - repository: devops
    endpoint: CodRepo
    type: git
    name: cod/Cod.Infrastructures
    ref: master

stages:
- stage: Production
  jobs:
  - template: pipelines/jobs/GenericDotnetBuild.yml@devops
    parameters:
      nugetVSTSFeedID: 'Niobium/niobium'
      projectToPublish: '**/Niobium.Billing.Functions.csproj'

  - template: pipelines/jobs/FunctionAppInfrastructure.yml@devops
    parameters:
      enabled: ${{ parameters.updateInfrastructure }}
      azureServiceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      appNamePrefix: 'niobiumbilling'
      enableKeyVault: true
      enableStagingSlot: true
      allowedOrigins: 'https://www.niobium.co.nz'
      checkoutDevopsStep:
        checkout: devops

  - job: Table
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
    steps:
    - checkout: devops
    - template: pipelines/steps/newStorageAccount.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        storageAccountName: 'niobiumbillingdb'
        contributorPrincipalId: $(functionAppPrincipalId)
        allowedOrigins: 'https://localhost:7182,https://billing.niobium.co.nz'

  - job: Configuration
    dependsOn:
      - Infrastructure
      - Table
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppName: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppName']]
      tableFQDN: $[dependencies.Table.outputs['newStorageAccountProperties.tableFQDN']]
      keyVaultUrl: $[dependencies.Infrastructure.outputs['infrastructureOutputs.keyVaultUrl']]
    steps:
    - checkout: none
    - task: AzureAppServiceSettings@1
      displayName: 'Update AppSettings'
      inputs:
        azureSubscription: $(serviceConnection)
        appName: $(functionAppName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            {
                "name": "ResendServiceOptions:GlobalAPIKey",
                "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/RESEND-API-KEY/)",
                "slotSetting": false
            },
            {
              "name": "StorageTableOptions:FullyQualifiedDomainName",
              "value": "$(tableFQDN)",
              "slotSetting": false
            },
            {
              "name": "StorageTableOptions:Key",
                "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/STORAGE-TABLE-KEY/)",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenAudience",
              "value": "95b52e52-dc79-4ac0-a53f-1acb10238888",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenPublicKey",
              "value": "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmuIHhRUT+IvTdTajuOEdPZ75pqJrajOyDdJqf42siofTKHCPCZqtWaftL8Jae5VMHUNCflXzm9aKTLgerAxrGyCL3BkZj/dj4KjbeFoY1Akz5EJd5qjRNtzdoqUkDsuaigJTDDhyHvdVKRHzYAJSKgiw9CLRkzyKDZAp1Fxm2xICzRoF9OfH0jv5Qn11gkMHrkVkB6nv7QD3EGS2rnDwKudjnlsvgjpoNMMNvY7EHqkuxjHdGh4Hy7M3UXl50Bft9ky3gKeCgpvVYRPXHdT6k3e+81J7liEJYdVb5taPeNf3wB8WCP8Xc7FO6vod9ziDIkJv+xqUWYtlyGZBGTBrQIDAQAB-----END PUBLIC KEY-----",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:AccessTokenSecret",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/ACCESS-TOKEN-SECRET/)",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:AccessTokenIssuer",
              "value": "Niobium.Billing.Functions",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:AccessTokenAudience",
              "value": "Niobium.Billing.Portal",
              "slotSetting": false
            },
            {
              "name": "BillingOptions:InvoiceTokenSecretSalt",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/INVOICE-TOKEN-SECRET-SALT/)",
              "slotSetting": false
            },
            {
              "name": "BillingOptions:GetInvoiceEndpoint",
              "value": "https://billing.niobium.co.nz",
              "slotSetting": false
            },
            {
              "name": "BillingOptions:InvoiceEmailSenderAddress",
              "value": "billing@niobium.co.nz",
              "slotSetting": false
            }
          ]
      
  - template: pipelines/jobs/FunctionAppDeploy.yml@devops
    parameters:
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
