name: '1.0$(Rev:.r)'
trigger:
- master

variables:
  buildAgentVmImage: 'windows-latest'
  serviceConnection: 'niobium-invoicing'
  resourceGroupName: 'niobium-invoicing'
  appName: 'niobiuminvoicingFunc'
  
  issueInvoiceCommandQueueName: 'issueinvoicecommand'
  notificationServiceBusResourceGroup: 'niobium-ntfy'
  enableStagingSlot: true
  
  tableDB: 'niobiuminvoicingdb'
  serviceBusNamespace: 'niobiuminvoicingsb'
  notificationServiceBusNamespace: 'niobiumntfysb'

  tableDBStaging: 'niobiuminvoicingdbstagin'
  serviceBusNamespaceStaging: 'niobiuminvoicingsbstaging'
  notificationServiceBusNamespaceStaging: 'niobiumntfysbstaging'

pool:
  vmImage: $(buildAgentVmImage)

resources: 
  repositories:
  - repository: devops
    endpoint: CodRepo
    type: git
    name: cod/Cod.Infrastructures
    ref: master

stages:
- stage: Production
  jobs:
  - template: pipelines/jobs/GenericDotnetBuild.yml@devops
    parameters:
      nugetVSTSFeedID: 'Niobium/niobium'
      projectToPublish: '**/Niobium.Invoicing.Functions.csproj'

  - template: pipelines/jobs/FunctionAppInfrastructure.yml@devops
    parameters:
      azureServiceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      appName: $(appName)
      enableKeyVault: true
      enableStagingSlot: ${{ variables.enableStagingSlot }}
      allowedOrigins: 'https://localhost:7182,https://invoicing.niobium.co.nz'
      checkoutDevopsStep:
        checkout: devops

  - job: Table
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
      functionAppPrincipalIdStaging: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalIdStaging']]
    steps:
    - checkout: devops
    - template: pipelines/steps/newStorageAccount.yml@devops
      parameters:
        sku: 'Standard_LRS'
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        storageAccountName: $(tableDB)
        contributorPrincipalId: $(functionAppPrincipalId)
        allowedOrigins: 'https://invoicing.niobium.co.nz'
        outputVariableName: 'newStorageAccountProperties'
    - template: pipelines/steps/newStorageAccount.yml@devops
      parameters:
        switch: ${{ variables.enableStagingSlot }}
        sku: 'Standard_LRS'
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        storageAccountName: $(tableDBStaging)
        contributorPrincipalId: $(functionAppPrincipalIdStaging)
        allowedOrigins: 'https://localhost:7182,https://invoicing.niobium.co.nz'
        outputVariableName: 'newStorageAccountPropertiesStaging'

  - job: Messaging
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
      functionAppPrincipalIdStaging: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalIdStaging']]
    steps:
    - checkout: devops
    - template: pipelines/steps/newServiceBus.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        serviceBusNamespaceName: $(serviceBusNamespace)
        serviceBusQueueNames: [$(issueInvoiceCommandQueueName)]
        dataOwnerPrincipalId: $(functionAppPrincipalId)
        outputVariableName: 'newServiceBusProperties'
    - template: pipelines/steps/newServiceBus.yml@devops
      parameters:
        switch: ${{ variables.enableStagingSlot }}
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(resourceGroupName)
        serviceBusNamespaceName: $(serviceBusNamespaceStaging)
        serviceBusQueueNames: [$(issueInvoiceCommandQueueName)]
        dataOwnerPrincipalId: $(functionAppPrincipalIdStaging)
        outputVariableName: 'newServiceBusPropertiesStaging'

  - job: NotificationRBAC
    dependsOn: 
      - Infrastructure
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      functionAppPrincipalId: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalId']]
      functionAppPrincipalIdStaging: $[dependencies.Infrastructure.outputs['infrastructureOutputs.functionAppPrincipalIdStaging']]
    steps:
    - checkout: devops
    - template: pipelines/steps/grantPermissionServiceBus.yml@devops
      parameters:
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(notificationServiceBusResourceGroup)
        serviceBusNamespaceName: $(notificationServiceBusNamespace)
        dataOwnerPrincipalId: $(functionAppPrincipalId)
        outputVariableName: 'serviceBusPermissionProperties'
    - template: pipelines/steps/grantPermissionServiceBus.yml@devops
      parameters:
        switch: ${{ variables.enableStagingSlot }}
        azureServiceConnection: $(serviceConnection)
        resourceGroupName: $(notificationServiceBusResourceGroup)
        serviceBusNamespaceName: $(notificationServiceBusNamespaceStaging)
        dataOwnerPrincipalId: $(functionAppPrincipalIdStaging)
        outputVariableName: 'serviceBusPermissionPropertiesStaging'

  - job: Configuration
    dependsOn:
      - Infrastructure
      - Table
      - Messaging
      - NotificationRBAC
    condition: succeeded()
    pool:
      vmImage: $(buildAgentVmImage)
    variables:
      keyVaultUrl: $[dependencies.Infrastructure.outputs['infrastructureOutputs.keyVaultUrl']]
      tableFQDN: $[dependencies.Table.outputs['newStorageAccountProperties.tableFQDN']]
      serviceBusFQDN: $[dependencies.Messaging.outputs['newServiceBusProperties.fullyQualifiedNamespace']]
      notificationServiceBusFQDN: $[dependencies.NotificationRBAC.outputs['serviceBusPermissionProperties.fullyQualifiedNamespace']]
      tableFQDNStaging: $[dependencies.Table.outputs['newStorageAccountPropertiesStaging.tableFQDN']]
      serviceBusFQDNStaging: $[dependencies.Messaging.outputs['newServiceBusPropertiesStaging.fullyQualifiedNamespace']]
      notificationServiceBusFQDNStaging: $[dependencies.NotificationRBAC.outputs['serviceBusPermissionPropertiesStaging.fullyQualifiedNamespace']]
    steps:
    - checkout: none
    - pwsh: Write-Output "##vso[task.setvariable variable=slotName;]production"
      displayName: "Deploy to Production"
      condition: eq('${{ variables.enableStagingSlot }}', false)
    - pwsh: Write-Output "##vso[task.setvariable variable=slotName;]staging"
      displayName: "Deploy to Staging"
      condition: eq('${{ variables.enableStagingSlot }}', true)
    - task: AzureAppServiceSettings@1
      displayName: 'Update AppSettings'
      inputs:
        azureSubscription: $(serviceConnection)
        appName: $(appName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            {
              "name": "IdentityServiceOptions:AccessTokenIssuer",
              "value": "Niobium.Invoicing.Functions",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:AccessTokenAudience",
              "value": "Niobium.Invoicing.Portal",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenAudience",
              "value": "95b52e52-dc79-4ac0-a53f-1acb10238888",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenPublicKey",
              "value": "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmuIHhRUT+IvTdTajuOEdPZ75pqJrajOyDdJqf42siofTKHCPCZqtWaftL8Jae5VMHUNCflXzm9aKTLgerAxrGyCL3BkZj/dj4KjbeFoY1Akz5EJd5qjRNtzdoqUkDsuaigJTDDhyHvdVKRHzYAJSKgiw9CLRkzyKDZAp1Fxm2xICzRoF9OfH0jv5Qn11gkMHrkVkB6nv7QD3EGS2rnDwKudjnlsvgjpoNMMNvY7EHqkuxjHdGh4Hy7M3UXl50Bft9ky3gKeCgpvVYRPXHdT6k3e+81J7liEJYdVb5taPeNf3wB8WCP8Xc7FO6vod9ziDIkJv+xqUWYtlyGZBGTBrQIDAQAB-----END PUBLIC KEY-----",
              "slotSetting": false
            },
            {
              "name": "ProfileOptions:ProfileServiceHost",
              "value": "https://api.identity.niobium.co.nz",
              "slotSetting": false
            },
            {
              "name": "ProfileOptions:ProfileAppID",
              "value": "e514f381-77cd-4ce9-ab6c-1a960fc7d9ed",
              "slotSetting": false
            },
            {
              "name": "BillingOptions:GetInvoiceEndpoint",
              "value": "https://api.invoicing.niobium.co.nz",
              "slotSetting": true
            },
            {
              "name": "StorageTableOptions:FullyQualifiedDomainName",
              "value": "$(tableFQDN)",
              "slotSetting": true
            },
            {
              "name": "ServiceBusOptions:FullyQualifiedNamespace",
              "value": "$(serviceBusFQDN)",
              "slotSetting": true
            },
            {
              "name": "ServiceBusTriggerOptions:FullyQualifiedNamespace",
              "value": "$(serviceBusFQDN)",
              "slotSetting": true
            },
            {
              "name": "NotificationQueueOptions:FullyQualifiedNamespace",
              "value": "$(notificationServiceBusFQDN)",
              "slotSetting": true
            },
            {
              "name": "BillingOptions:InvoiceTokenSecretSalt",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/INVOICE-TOKEN-SECRET-SALT/)",
              "slotSetting": true
            },
            {
              "name": "IdentityServiceOptions:AccessTokenSecret",
              "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/ACCESS-TOKEN-SECRET/)",
              "slotSetting": true
            },
            {
                "name": "ResendServiceOptions:GlobalAPIKey",
                "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/RESEND-API-KEY/)",
                "slotSetting": true
            },
            {
              "name": "StorageTableOptions:Key",
                "value": "@Microsoft.KeyVault(SecretUri=$(keyVaultUrl)/secrets/STORAGE-TABLE-KEY/)",
              "slotSetting": true
            }
          ]
    - task: AzureAppServiceSettings@1
      displayName: 'Update $(slotName) AppSettings'
      inputs:
        azureSubscription: $(serviceConnection)
        appName: $(appName)
        slotName: $(slotName)
        resourceGroupName: $(resourceGroupName)
        appSettings: |
          [
            {
              "name": "BillingOptions:InvoiceTokenSecretSalt",
              "value": "1234567890",
              "slotSetting": true
            },
            {
              "name": "IdentityServiceOptions:AccessTokenSecret",
              "value": "012345678901234567890123456789AB",
              "slotSetting": true
            },
            {
              "name": "AzureWebJobs.IssueInvoiceCommandConsumer.Disabled",
              "value": "true",
              "slotSetting": true
            },
            {
              "name": "StorageTableOptions:FullyQualifiedDomainName",
              "value": "$(tableFQDNStaging)",
              "slotSetting": true
            },
            {
              "name": "ServiceBusOptions:FullyQualifiedNamespace",
              "value": "$(serviceBusFQDNStaging)",
              "slotSetting": true
            },
            {
              "name": "ServiceBusTriggerOptions:FullyQualifiedNamespace",
              "value": "$(serviceBusFQDNStaging)",
              "slotSetting": true
            },
            {
              "name": "NotificationQueueOptions:FullyQualifiedNamespace",
              "value": "$(notificationServiceBusFQDNStaging)",
              "slotSetting": true
            },
            {
              "name": "BillingOptions:GetInvoiceEndpoint",
              "value": "https://staging.api.invoicing.niobium.co.nz",
              "slotSetting": true
            },
            {
              "name": "IdentityServiceOptions:AccessTokenIssuer",
              "value": "Niobium.Invoicing.Functions",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:AccessTokenAudience",
              "value": "Niobium.Invoicing.Portal",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenAudience",
              "value": "95b52e52-dc79-4ac0-a53f-1acb10238888",
              "slotSetting": false
            },
            {
              "name": "IdentityServiceOptions:IDTokenPublicKey",
              "value": "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmuIHhRUT+IvTdTajuOEdPZ75pqJrajOyDdJqf42siofTKHCPCZqtWaftL8Jae5VMHUNCflXzm9aKTLgerAxrGyCL3BkZj/dj4KjbeFoY1Akz5EJd5qjRNtzdoqUkDsuaigJTDDhyHvdVKRHzYAJSKgiw9CLRkzyKDZAp1Fxm2xICzRoF9OfH0jv5Qn11gkMHrkVkB6nv7QD3EGS2rnDwKudjnlsvgjpoNMMNvY7EHqkuxjHdGh4Hy7M3UXl50Bft9ky3gKeCgpvVYRPXHdT6k3e+81J7liEJYdVb5taPeNf3wB8WCP8Xc7FO6vod9ziDIkJv+xqUWYtlyGZBGTBrQIDAQAB-----END PUBLIC KEY-----",
              "slotSetting": false
            },
            {
              "name": "ProfileOptions:ProfileServiceHost",
              "value": "https://api.identity.niobium.co.nz",
              "slotSetting": false
            },
            {
              "name": "ProfileOptions:ProfileAppID",
              "value": "e514f381-77cd-4ce9-ab6c-1a960fc7d9ed",
              "slotSetting": false
            }
          ]

  - template: pipelines/jobs/FunctionAppDeploy.yml@devops
    parameters:
      appName: $(appName)
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      enableStagingSlot: ${{ variables.enableStagingSlot }}
      autoSwapSlots: true