<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Niobium.Invoicing</RootNamespace>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <NoWarn>CA1848,CA2254,CA1305,CA1310,CA1711,CA1852,CS8618</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NeutralLanguage>en-US</NeutralLanguage>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="InvoiceTemplate.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="Niobium.Notification.Contracts" Version="1.0.105" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Niobium.Invoicing.Contracts\Niobium.Invoicing.Contracts.csproj" />
  </ItemGroup>

</Project>
