name: Publish

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: 'test'
    concurrency:
      group: test-deploy
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install azd
        uses: Azure/setup-azd@v2
        
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: azd login
        run: azd auth login --federated-credential-provider github --client-id ${{ secrets.AZURE_CLIENT_ID }} --tenant-id ${{ secrets.AZURE_TENANT_ID }}

      - name: Publish
        env:
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_ENV_NAME: 'test'
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          IS_INTERACTIVE_DEPLOYER: false
          CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
          APPSETTING_SERVICE_NAME: 'Niobium.Invoicing.Server.Test'
          APPSETTING_SERVICE_VERSION: '1.0.${{ github.run_number }}-prerelease'
          APPSETTING_BILLINGOPTIONS__GETINVOICEENDPOINT: 'https://staging.api.invoicing.niobium.co.nz'
          APPSETTING_IDENTITYSERVICEOPTIONS__ACCESSTOKENAUDIENCE: 'Niobium.Invoicing.Client.Test'
          APPSETTING_IDENTITYSERVICEOPTIONS__ACCESSTOKENISSUER: 'Niobium.Invoicing.Server.Test'
          APPSETTING_IDENTITYSERVICEOPTIONS__IDTOKENAUDIENCE: '95b52e52-dc79-4ac0-a53f-1acb10238888'
          APPSETTING_IDENTITYSERVICEOPTIONS__IDTOKENPUBLICKEY: '-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmuIHhRUT+IvTdTajuOEdPZ75pqJrajOyDdJqf42siofTKHCPCZqtWaftL8Jae5VMHUNCflXzm9aKTLgerAxrGyCL3BkZj/dj4KjbeFoY1Akz5EJd5qjRNtzdoqUkDsuaigJTDDhyHvdVKRHzYAJSKgiw9CLRkzyKDZAp1Fxm2xICzRoF9OfH0jv5Qn11gkMHrkVkB6nv7QD3EGS2rnDwKudjnlsvgjpoNMMNvY7EHqkuxjHdGh4Hy7M3UXl50Bft9ky3gKeCgpvVYRPXHdT6k3e+81J7liEJYdVb5taPeNf3wB8WCP8Xc7FO6vod9ziDIkJv+xqUWYtlyGZBGTBrQIDAQAB-----END PUBLIC KEY-----'
          APPSETTING_PROFILEOPTIONS__PROFILEAPPID: 'e514f381-77cd-4ce9-ab6c-1a960fc7d9ed'
          APPSETTING_PROFILEOPTIONS__PROFILESERVICEHOST: 'https://api.identity.niobium.co.nz'
          APPSETTING_NOTIFICATIONQUEUEOPTIONS__FULLYQUALIFIEDNAMESPACE: 'niobiumnotify-test-sbns.servicebus.windows.net'
          APPSETTING_BILLINGOPTIONS__INVOICETOKENSECRETSALT: '1234567890'
          APPSETTING_KV_IDENTITYSERVICEOPTIONS__ACCESSTOKENSECRET: '012345678901234567890123456789AB'
        run: |
          azd package --no-prompt
          azd provision --no-state --no-prompt
          azd deploy --no-prompt
  prod:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: 'prod'
    concurrency:
      group: production-deploy
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: azd login
        run: azd auth login --federated-credential-provider github --client-id ${{ secrets.AZURE_CLIENT_ID }} --tenant-id ${{ secrets.AZURE_TENANT_ID }}

      - name: Publish
        env:
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_ENV_NAME: 'prod'
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
          IS_INTERACTIVE_DEPLOYER: false
          APPSETTING_SERVICE_NAME: 'Niobium.Invoicing.Server.Prod'
          APPSETTING_SERVICE_VERSION: '1.0.${{ github.run_number }}'
          APPSETTING_BILLINGOPTIONS__GETINVOICEENDPOINT: 'https://api.invoicing.niobium.co.nz'
          APPSETTING_IDENTITYSERVICEOPTIONS__ACCESSTOKENAUDIENCE: 'Niobium.Invoicing.Client.Prod'
          APPSETTING_IDENTITYSERVICEOPTIONS__ACCESSTOKENISSUER: 'Niobium.Invoicing.Server.Prod'
          APPSETTING_IDENTITYSERVICEOPTIONS__IDTOKENAUDIENCE: '95b52e52-dc79-4ac0-a53f-1acb10238888'
          APPSETTING_IDENTITYSERVICEOPTIONS__IDTOKENPUBLICKEY: '-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmuIHhRUT+IvTdTajuOEdPZ75pqJrajOyDdJqf42siofTKHCPCZqtWaftL8Jae5VMHUNCflXzm9aKTLgerAxrGyCL3BkZj/dj4KjbeFoY1Akz5EJd5qjRNtzdoqUkDsuaigJTDDhyHvdVKRHzYAJSKgiw9CLRkzyKDZAp1Fxm2xICzRoF9OfH0jv5Qn11gkMHrkVkB6nv7QD3EGS2rnDwKudjnlsvgjpoNMMNvY7EHqkuxjHdGh4Hy7M3UXl50Bft9ky3gKeCgpvVYRPXHdT6k3e+81J7liEJYdVb5taPeNf3wB8WCP8Xc7FO6vod9ziDIkJv+xqUWYtlyGZBGTBrQIDAQAB-----END PUBLIC KEY-----'
          APPSETTING_PROFILEOPTIONS__PROFILEAPPID: 'e514f381-77cd-4ce9-ab6c-1a960fc7d9ed'
          APPSETTING_PROFILEOPTIONS__PROFILESERVICEHOST: 'https://api.identity.niobium.co.nz'
          APPSETTING_NOTIFICATIONQUEUEOPTIONS__FULLYQUALIFIEDNAMESPACE: 'niobiumnotify-prod-sbns.servicebus.windows.net'
          APPSETTING_KV_BILLINGOPTIONS__INVOICETOKENSECRETSALT: ${{ secrets.APPSETTING_BILLINGOPTIONS__INVOICETOKENSECRETSALT }}
          APPSETTING_KV_IDENTITYSERVICEOPTIONS__ACCESSTOKENSECRET: ${{ secrets.APPSETTING_IDENTITYSERVICEOPTIONS__ACCESSTOKENSECRET }}
          APPSETTING_KV_RESENDSERVICEOPTIONS__GLOBALAPIKEY: ${{ secrets.APPSETTING_RESENDSERVICEOPTIONS__GLOBALAPIKEY }}
          APPSETTING_KV_STORAGETABLEOPTIONS__KEY: ${{ secrets.APPSETTING_STORAGETABLEOPTIONS__KEY }}
        run: |
          azd package --no-prompt
          azd provision --no-state --no-prompt
          azd deploy --no-prompt